version: '3.8'

services:
  app_antojos:
    image: antojos-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      # DB_URL: jdbc:mysql://db:3306/b98t1weohq60v7wxm6wz
      DB_URL: jdbc:mysql://uh4dxqseiss6qykp:c9gfwxCulN0dzPWVvZlW@bp1mi2fytyu7mg0bjjcb-mysql.services.clever-cloud.com:3306/bp1mi2fytyu7mg0bjjcb
      DB_USER_NAME: uh4dxqseiss6qykp
      DB_PASSWORD: c9gfwxCulN0dzPWVvZlW
    
  db:
    image: mysql:8.1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: c9gfwxCulN0dzPWVvZlW
      # MYSQL_DATABASE: b98t1weohq60v7wxm6wz
      MYSQL_DATABASE: bp1mi2fytyu7mg0bjjcb
      MYSQL_USER: uh4dxqseiss6qykp
      MYSQL_PASSWORD: c9gfwxCulN0dzPWVvZlW
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
